//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IADP.MoHra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.IssuesAssigned = new HashSet<Issue>();
            this.IssuesAuthor = new HashSet<Issue>();
            this.MemberParent = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LeadMemberId { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public System.DateTime DateStart { get; set; }
        public bool UseForParticipationAutoFill { get; set; }
        public Nullable<int> RedmineMemberId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> IssuesAssigned { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> IssuesAuthor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> MemberParent { get; set; }
        public virtual Member MemberChilds { get; set; }
    }
}
