//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IADP.MoHra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revision()
        {
            this.IssueRevisions = new HashSet<IssueRevision>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int MemberId { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueRevision> IssueRevisions { get; set; }
        public virtual Member Member { get; set; }
    }
}
